permalink: /:year/:month/:day/:title
paginate: 10
exclude: ["Makefile", "LICENSE.txt", "less", "NOTES.txt", "inscriptions_2012_05_31.ods", "logo_twitter.png", "svg", "draft", "docs"]
title: LoOPS
url: http://reseau-loops.github.com
markdown: rdiscount
